### PR TITLE
Update to CLDR 34 format and clean up

### PR DESCRIPTION
**Pull request by Korri**
The goal here is to tag a new version after this PR, which changes/fixes a few things:

* Update to version 34 of CLDR (not sure I checked everything necessary here)
* Use the `yaml` package instead of the dead `ya2yaml` gem (fixes: https://github.com/svenfuchs/ruby-cldr/issues/44)
* Updated the test suite and dependencies

### CODE REVIEW

**Comment by Korri** [comment]
Ping @camertron, @tigrish do you think we can merge this?

**Comment by camertron** [comment]
@Korri thanks for your contributions! This looks 👍 to me, but I do have one question: the ya2yaml gem, while unmaintained, was used in the project (if I remember correctly) because it handles Unicode more gracefully/completely than Psych. I didn't see anything in my cursory examination of the YAML files that have changed in this PR, but would you mind just verifying that all Unicode strings look ok?

Also, I don't actually have approval or merge permissions on this repo, so we're going to have to wait for @tigrish to weigh in.

**Comment by Korri** [comment]
@camertron I added a test to cover unicode encoding, it seems to work fine but I'm not sure as I don't know what has been causing issues in the past.

**Comment by camertron** [comment]
@Korri actually now that I think back I believe the Unicode issues were with Ruby 1.8... so not worth worrying about. This PR looks good to me.

**Comment by Korri** [comment]
@camertron thanks! Any chance we can tag a new version?

**Comment by camertron** [comment]
@Korri again, I don't have permissions to do that. We'll need to ask @tigrish.

**Comment by Korri** [comment]
Sorry about that, I mixed the usernames up 😞

**Comment by camertron** [comment]
Ah I see, no worries :)

**Pull request merged**
